
import { Language } from './types';

export const TRANSLATIONS = {
  [Language.CN]: {
    appTitle: "矿井智能巡检系统",
    dashboard: "控制台",
    inspection: "算法与数据",
    settings: "系统设置",
    modeFlight: "飞行模式",
    modeTrack: "履带模式",
    statusOnline: "在线",
    statusOffline: "离线",
    battery: "电量",
    signal: "信号",
    altitude: "高度",
    speed: "速度",
    distance: "行进距离",
    gasLevel: "瓦斯浓度 (GNN重构)",
    gasRaw: "原始测量 (IDW)",
    temp: "环境温度",
    humidity: "空气湿度",
    obstacle: "障碍物距离",
    switchMode: "切换模式",
    cameraFeed: "实时图传",
    slamMap: "LIO-SLAM 实时建图",
    trajectory: "巡检轨迹",
    riskMap: "瓦斯风险热力图",
    startEngine: "启动引擎",
    stopEngine: "紧急停止",
    systemLog: "系统日志",
    initializing: "正在初始化传感器阵列...",
    calibrating: "IMU 零偏校准中 (Step 1.1)...",
    ready: "系统就绪",
    gasReconstruction: "瓦斯场动态重构 (Step 2)",
    semanticAnalysis: "语义几何融合分析 (Step 3)",
    traversability: "通行能力决策",
    passable: "可通行",
    unreachable: "不可通行",
    language: "语言选择",
    // Algorithm Specific
    algoLoc: "定位鲁棒性 (Step 1)",
    algoGas: "浓度场重构 (Step 2)",
    algoTrav: "通行性分析 (Step 3)",
    rmse: "配准误差 (RMSE)",
    featureDens: "特征点密度 (ρ)",
    hydDiam: "水力直径 (Dh)",
    slope: "地面坡度 (θ)",
    stepH: "台阶高度 (H)",
    roughness: "表面粗糙度 (σ)",
    // Config Modal
    configTitle: "算法参数配置",
    configDesc: "调整机器人通行性分析的决策阈值 (Step 3)",
    maxSlope: "最大爬坡角度 (θ)",
    maxStep: "最大台阶高度 (H)",
    maxRough: "最大允许粗糙度 (σ)",
    save: "应用配置",
    cancel: "取消",
    // Connection Module
    hardwareConnection: "硬件连接",
    connectStm32: "连接 STM32 控制板",
    disconnectStm32: "断开连接",
    connectionStatus: "连接状态",
    connected: "已连接",
    disconnected: "未连接",
    connecting: "连接中...",
    connectionError: "连接失败",
    baudRate: "波特率",
    dataPreview: "数据预览 (HEX/ASCII)",
    noData: "暂无数据输入...",
    sendTest: "发送测试指令",
    deviceInfo: "设备信息",
    // WebSocket / Car Control
    robotControl: "机器人控制",
    connectCar: "连接小车 (WebSocket)",
    disconnectCar: "断开小车",
    wsAddress: "WebSocket 地址",
    wsStatus: "网络连接",
    cmdForward: "前进",
    cmdBackward: "后退",
    cmdLeft: "左转",
    cmdRight: "右转",
    cmdUp: "上升",
    cmdDown: "下降",
    cmdStop: "停止",
    flightControls: "飞行控制",
    trackControls: "履带控制",
    // Warnings
    highTemp: "高温警报",
  },
  [Language.EN]: {
    appTitle: "MineGuard AI System",
    dashboard: "Console",
    inspection: "Algo & Data",
    settings: "Settings",
    modeFlight: "Flight Mode",
    modeTrack: "Track Mode",
    statusOnline: "Online",
    statusOffline: "Offline",
    battery: "Battery",
    signal: "Signal",
    altitude: "Altitude",
    speed: "Speed",
    distance: "Distance",
    gasLevel: "Methane (GNN)",
    gasRaw: "Raw Sensor (IDW)",
    temp: "Temperature",
    humidity: "Humidity",
    obstacle: "Obstacle Dist.",
    switchMode: "Switch Mode",
    cameraFeed: "Live Feed",
    slamMap: "Real-time LIO-SLAM",
    trajectory: "Trajectory",
    riskMap: "Gas Risk Heatmap",
    startEngine: "Start Engine",
    stopEngine: "Emergency Stop",
    systemLog: "System Log",
    initializing: "Initializing sensor array...",
    calibrating: "Calibrating IMU bias (Step 1.1)...",
    ready: "System Ready",
    gasReconstruction: "Gas Field Reconstruction (Step 2)",
    semanticAnalysis: "Geometric-Semantic Analysis (Step 3)",
    traversability: "Traversability",
    passable: "Passable",
    unreachable: "Blocked",
    language: "Language",
    // Algorithm Specific
    algoLoc: "Localization Robustness (Step 1)",
    algoGas: "Field Reconstruction (Step 2)",
    algoTrav: "Traversability Analysis (Step 3)",
    rmse: "Registration RMSE",
    featureDens: "Feature Density (ρ)",
    hydDiam: "Hydraulic Dia. (Dh)",
    slope: "Terrain Slope (θ)",
    stepH: "Step Height (H)",
    roughness: "Roughness (σ)",
    // Config Modal
    configTitle: "Algorithm Configuration",
    configDesc: "Adjust decision thresholds for traversability analysis (Step 3)",
    maxSlope: "Max Slope Angle (θ)",
    maxStep: "Max Step Height (H)",
    maxRough: "Max Roughness (σ)",
    save: "Apply Config",
    cancel: "Cancel",
    // Connection Module
    hardwareConnection: "Hardware Connection",
    connectStm32: "Connect STM32",
    disconnectStm32: "Disconnect",
    connectionStatus: "Status",
    connected: "Connected",
    disconnected: "Disconnected",
    connecting: "Connecting...",
    connectionError: "Connection Error",
    baudRate: "Baud Rate",
    dataPreview: "Data Preview (HEX/ASCII)",
    noData: "No data received...",
    sendTest: "Send Test Command",
    deviceInfo: "Device Info",
    // WebSocket / Car Control
    robotControl: "Robot Control",
    connectCar: "Connect Car (WS)",
    disconnectCar: "Disconnect Car",
    wsAddress: "WebSocket Address",
    wsStatus: "Network Link",
    cmdForward: "Forward",
    cmdBackward: "Backward",
    cmdLeft: "Left",
    cmdRight: "Right",
    cmdUp: "Ascend",
    cmdDown: "Descend",
    cmdStop: "Stop",
    flightControls: "Flight Controls",
    trackControls: "Track Controls",
    // Warnings
    highTemp: "High Temp Warning",
  },
  [Language.DE]: {
    appTitle: "Mineninspektionssystem",
    dashboard: "Konsole",
    inspection: "Algo & Daten",
    settings: "Einstellungen",
    modeFlight: "Flugmodus",
    modeTrack: "Raupenmodus",
    statusOnline: "Online",
    statusOffline: "Offline",
    battery: "Batterie",
    signal: "Signal",
    altitude: "Höhe",
    speed: "Geschwindigkeit",
    distance: "Entfernung",
    gasLevel: "Methan (GNN)",
    gasRaw: "Rohdaten (IDW)",
    temp: "Temperatur",
    humidity: "Feuchtigkeit",
    obstacle: "Hindernisabst.",
    switchMode: "Modus wechseln",
    cameraFeed: "Live-Übertragung",
    slamMap: "Echtzeit-LIO-SLAM",
    trajectory: "Flugbahn",
    riskMap: "Gasrisiko-Heatmap",
    startEngine: "Motor starten",
    stopEngine: "Not-Halt",
    systemLog: "Systemprotokoll",
    initializing: "Sensorarray wird initialisiert...",
    calibrating: "IMU-Bias-Kalibrierung (Schritt 1.1)...",
    ready: "System bereit",
    gasReconstruction: "Gasfeld-Rekonstruktion (Schritt 2)",
    semanticAnalysis: "Semantische Analyse (Schritt 3)",
    traversability: "Passierbarkeit",
    passable: "Passierbar",
    unreachable: "Blockiert",
    language: "Sprache",
    // Algorithm Specific
    algoLoc: "Lokalisierungsrobustheit (Schritt 1)",
    algoGas: "Feldrekonstruktion (Schritt 2)",
    algoTrav: "Passierbarkeitsanalyse (Schritt 3)",
    rmse: "Registrierung RMSE",
    featureDens: "Feature-Dichte (ρ)",
    hydDiam: "Hydraulischer Durchm. (Dh)",
    slope: "Hangneigung (θ)",
    stepH: "Stufenhöhe (H)",
    roughness: "Rauheit (σ)",
    // Config Modal
    configTitle: "Algorithmus-Konfiguration",
    configDesc: "Entscheidungsschwellenwerte für Passierbarkeit anpassen (Schritt 3)",
    maxSlope: "Max. Neigungswinkel (θ)",
    maxStep: "Max. Stufenhöhe (H)",
    maxRough: "Max. Rauheit (σ)",
    save: "Konfig. anwenden",
    cancel: "Abbrechen",
    // Connection Module
    hardwareConnection: "Hardware-Verbindung",
    connectStm32: "STM32 Verbinden",
    disconnectStm32: "Trennen",
    connectionStatus: "Status",
    connected: "Verbunden",
    disconnected: "Getrennt",
    connecting: "Verbinden...",
    connectionError: "Verbindungsfehler",
    baudRate: "Baudrate",
    dataPreview: "Datenvorschau (HEX/ASCII)",
    noData: "Keine Daten empfangen...",
    sendTest: "Testbefehl senden",
    deviceInfo: "Geräteinformation",
    // WebSocket / Car Control
    robotControl: "Robotersteuerung",
    connectCar: "Auto Verbinden (WS)",
    disconnectCar: "Auto Trennen",
    wsAddress: "WebSocket Adresse",
    wsStatus: "Netzwerkverbindung",
    cmdForward: "Vorwärts",
    cmdBackward: "Rückwärts",
    cmdLeft: "Links",
    cmdRight: "Rechts",
    cmdUp: "Steigen",
    cmdDown: "Sinken",
    cmdStop: "Stopp",
    flightControls: "Flugsteuerung",
    trackControls: "Raupensteuerung",
    // Warnings
    highTemp: "Warnung: Hohe Temp.",
  }
};
